name: Backend CI/CD

on:
  push:
    branches:
      - dev

jobs:

  ci:
    name: Build Backend
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests


  deploy:
    name: Deploy Backend
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose up -d --build backend
          docker compose ps